name: Label PRs
on:
  pull_request:
    types: [opened, edited]
jobs:
  labels-prs:
    name: Label PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: illicitonion/pr-action@main
        with:
          pr_title: ${{ github.event.pull_request.title }}
          pr_body: ${{ github.event.pull_request.body }}
